"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PYNBM.py']
DATA_FILES = ['Images','Extensions.defaults','ftp-mac.scpt','telnet-mac.scpt','ssh-mac.scpt','license.txt']
OPTIONS = {'argv_emulation': True,
 'iconfile': 'Images/Polling.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

